### ISSUE TITLE
Are there any merged spectra or will there be any merged spectra in the future?

### ISSUE THREAD

**Issue by meier-rene** [MassBank/MassBank-web#127]
Currently MassBank reports zero merged spectra. https://massbank.eu/MassBank/RecordIndex.html Is there a bug in the code? Does anyone know about merged spectra in MassBank? Will there be any merged Spectra in the future? Are there plans to actually merge spectra?
Or should we remove the unused property 'merged'?

**Comment by schymane** [comment]
There certainly were merged records historically ... but they may have been removed due to license issues. Merging was part of their way of being able to release the data at all. It is a common procedure in proteomics and also in some other libraries, so I think we should keep this category even if it has not apparent current use.

**Comment by takaakin** [comment]
"Merged spectra" is defined in 708 page of the first report of MassBank, Horai et al., (2010), http://dx.doi.org/10.1002/jms.1777 .

 In short, they were created to show all the observed peaks in the MS/MS spectra analyzed on a same chemical compound but different analytical conditions of CID energies. They were accidentally lost after the publication.

Takaaki Nishioka
 
07/11/18 05:08 午後 に、René Meier <notifications@github.com> さんは書きました:

**Comment by Treutler** [comment]
Thank you for the clarification.
