### ISSUE TITLE
Catch outdated urls

### ISSUE THREAD

**Issue by tsufz** [MassBank/MassBank-web#14]
Hi,
I want to catch outdate urls and redirected them to the short link:

An example:
http://massbank.eu/MassBank/jsp/Dispatcher.jsp?type=disp&id=KOX00513&site=5

Ends up to a zombie page, because the internal order of DBs changed and the id cannot be found in the site (=DB) 5.

My idea is to redirected the request to:
http://massbank.eu/MassBank/jsp/FwdRecord.jsp?id=KOX00513

I think the best is too use the Apache vhost.conf by writing a RewriteRule such as:
RewriteRule ^(.*)$ http://massbank.eu$1 [R=301,NE]

As I am a RegEx dummy someone may help me to extract the id from the url:
RewriteRule ^?????$ http://massbank.eu/MassBank/jsp/FwdRecord.jsp?id=$1 [R=301,NE]

Thanks,
Tobias

**Comment by ermueller** [comment]
What are the paths relative to, if you put it in vhosts.conf? Or does it take the full path?

I'm not 100% sure, since I can't test it, but something like this (if the path is relative to http://massbank.eu/MassBank/), at least the regular expression in the brackets for the ID should be right.

````
RewriteRule ^jsp/Dispatcher\.jsp\?.*([A-Z]{2,3}[0-9]{5,6}).*$ http://massbank.eu/MassBank/jsp/FwdRecord.jsp?id=$1 [NE,R=301,PT]
````
There are problems with redirecting **from** .jsp though, since under some circumstances tomcat takes the URL directly without it passing through the apache (and therefore RewriteRule) beforehand.

**Comment by tsufz** [comment]
> There are problems with redirecting *from* .jsp though, since under some
 > circumstances tomcat takes the URL directly without it passing through
 > the apache (and therefore RewriteRule) beforehand.


Yeah, actually you are right, Tomcat handles the query and does not pass 
to Apache... Okay, that's why my own trials were not sucessfully...

Thanks!

**Comment by tsufz** [comment]
But wait, interestingly Apache handles 
http://massbank.ufz.de/MassBank/jsp/Dispatcher.jsp?type=disp&id=KOX00513&site=5

and rewrites to
http://massbank.eu/MassBank/jsp/Dispatcher.jsp?type=disp&id=KOX00513&site=5

Hence, Apache gets the request at some point... Okay, I have a view on the logs...

**Comment by tsufz** [comment]
Tomcat has also an url handling option:
http://tuckey.org/urlrewrite/

**Comment by sneumann** [comment]
After some discussion we (Tobias, Erik and Steffen) concluded that we'll rather wait 
until the outdated URLs are gone from google.
