### ISSUE TITLE
Refine MassBank-web deployment

### ISSUE THREAD

**Issue by Treutler** [MassBank/MassBank-web#169]
Tobias and me have the feeling that the deployment of MassBank.eu could be refined in two ways:
- automate all steps in the deployment by a script
- built the updated MassBank while preserving the old MassBank and switch the old instance with the new instance when the new instance was built completely without error

**Comment by meier-rene** [comment]
Full Agreement. We need to select automatic rollout mechanism and than I can prepare the respective files.

For the development server I use vagrant and @sneumann has configured our apache to redirect all traffic from a specific URL to this system.

As far as I know @tsufz is running just one system and it would be rather complicated for you to organize another system. This means rollout of several vagrant provisioned vms is not the best easiest possibility for you.

That's why I propose, that I create an automatic docker-compose rollout mechanism similar to our dev rollouts(In fact its more or less finished). These container can happily coexist on one machine and we can just use Tobias' existing infrastructure.

@tsufz Could you please tell me how the traffic from https://massbank.eu/MassBank/ gets redirected to your server system?
Do you think its easily possible for you to change this redirection mechanism to point to a new rollout of MassBank on a regular basis? Or do we need to put another redirection in between?

**Comment by tsufz** [comment]
I have two systems. They are clones and I test updates first on the internal server. I cannot setup a second server in the accessible sector, thus the second runs on the internal cluster.

n docker instances sound cool, might be the way to run embargo DBs. I send you the apache file which still redirects the requests.

**Comment by meier-rene** [comment]
I have implemented a easy deployment method and updated the [documentation](https://github.com/MassBank/MassBank-web#install-as-server-system-with-dockermultiple-instances-on-one-server-possible). With this new method its possible to install completely independent MassBank-instances in separated subnets within docker with just a single command. Our [development](https://msbi.ipb-halle.de/MassBank) server is using this method now. @tsufz , you can directly use your existing systems for massbank.eu, because they should already meet all the requirements. I'm closing this now. In case of any problems contact me by email or reopen.
