### ISSUE TITLE
sitemaps broken

### ISSUE THREAD

**Issue by tsufz** [MassBank/MassBank-web#244]
@meier-rene, the site maps look broken to me. There are missing slashes and why does it not generate in the general sitemap schema https://www.sitemaps.org/protocol.html as before? The entries could not be fetched:
![image](https://user-images.githubusercontent.com/2526819/81728337-925a2380-948a-11ea-9b14-fbe8b04e2754.png)

See: https://massbank.eu/MassBank/sitemap/sitemap1.xml

Furthermore, the common name for the sitemap index is sitemapindex.xml and not sitemap-index.xml (https://www.sitemaps.org/protocol.html#index)

I think, we should be compliant with the schema to quarantee that all crawlers find the sitemaps. I dunno if they work with wildcards to find sitemaps. I only maintain Bing and Google.

**Comment by tsufz** [comment]
I was actually wondering why Google is delivering the old presentation and not the new one:
https://www.google.com/search?client=firefox-b-d&q=diclofenac+massbank
https://massbank.eu/MassBank/RecordDisplay.jsp?id=EA020111.

Now, it is clear, that the cause is the broken sitemap.

**Comment by meier-rene** [comment]
Hi @tsufz , I fixed this issue, created a new release and merged the new release to massbank.eu branch. Please roll out whenever you have time.
Make sure you adjust the settings in the google search console after rollout. Here comes a short explanation: 

- There were two issues here. First thing is the missing slashes. I specified the slash in the massbank.conf file and apparently you gave the URL without slash. In the future the slashes will be checked and added if needed.

- The naming of the sitemaps is now changed. You requested a "standard" behavior of the name of the sitemap. Its now `sitemap.xml`, which is probably the most "standard" name. In our case its a sitemap index file, which defines the actual sitemap files in the location .../MassBank/sitemap/{sitemap, sitemap1, sitemap2}.xml. So please check if its working in your installation after deployment. Make sure you adjust your sitemap at google, so that their robots can find the new sitemap and remove the old sitemap location.

Please make a complete rollout **with** database, because there were some changes in the database due to #242.

Please close if everything is fine.

**Comment by tsufz** [comment]
Hi @meier-rene, thanks for the update! Is the name sitemap.xml really working? Regarding to sitemaps.org, sitmemapindex.xml is the official index for many single sitemaps. https://www.sitemaps.org/protocol.html#sitemapIndex_sitemapindex

**Comment by tsufz** [comment]
@meier-rene, the sitemaps do not yet working properly. I really don't understand why the index file is not named sitemapindex.xml and why the sitemaps itself do not contain the scheme tags? I think the sitemaps generated are failing. Please follow the conventions. Everything worked with the old sitemaps before the implementation in Java. 
![image](https://user-images.githubusercontent.com/2526819/82425761-43fae500-9a87-11ea-95d9-168ae643deb3.png)

**Comment by tsufz** [comment]
![image](https://user-images.githubusercontent.com/2526819/82425903-73a9ed00-9a87-11ea-97ad-19befebe7988.png)

**Comment by tsufz** [comment]
@meier-rene, the sitemaps do not yet working properly. I really don't understand why the index file is not named sitemapindex.xml and why the sitemaps itself do not contain the scheme tags? I think the sitemaps generated are failing. Please follow the conventions. Everything worked with the old sitemaps before the implementation in Java.
![image](https://user-images.githubusercontent.com/2526819/82425924-7ad0fb00-9a87-11ea-8628-d54a09193871.png)
![image](https://user-images.githubusercontent.com/2526819/82426010-96d49c80-9a87-11ea-86ca-afb3a75e7b70.png)

The sitemaps can be fetched:
![image](https://user-images.githubusercontent.com/2526819/82426255-e7e49080-9a87-11ea-9bab-eb07ebdbe78e.png)

**Comment by meier-rene** [comment]
Hi @tsufz ,
first regarding the name: I can call the sitemap index whatever you want, but I really can not find a official naming scheme. https://www.sitemaps.org/protocol.html#sitemapIndex_sitemapindex doesn't even mention a sitemapindex.xml. I don't think, that the problems have anything to do with naming, but I will change it to sitemapindex.xml and try again.

Besides that, google should procss the sitemaps, but it also fails in some way on our dev server. 
![image](https://user-images.githubusercontent.com/25176376/82438037-b58f5f00-9a98-11ea-8f1b-02e3d34fb240.png)

I don't know whats the problem at the moment.

**Comment by tsufz** [comment]
Hi!
I am a little bit wondering, all schemas are on that page:
![image](https://user-images.githubusercontent.com/2526819/82649441-82280e00-9c19-11ea-9b3e-a00caf89fd04.png)
![image](https://user-images.githubusercontent.com/2526819/82649489-93711a80-9c19-11ea-8cb2-89d9e3c8b63b.png)
Best,
Tobias

**Comment by tsufz** [comment]
@ermueller implemented this scheme once in MassBank a we had an R script running it.
