### ISSUE TITLE
SEO: Provide a sitemap.xml for a list of valid URLs 

### ISSUE THREAD

**Issue by newgene** [MassBank/MassBank-web#307]
As part of [BioSchemas](https://BioSchemas.org) and [Data Discovery Engine](https://discovery.biothings.io) (DDE) efforts, we would like to crawl through the resource pages provided from MassBank and validate the JSON-LD metadata compliant with schema.org, e.g., a page like this:

https://massbank.eu/MassBank/RecordDisplay?id=LQB00001&dsn=RIKEN_IMS

This is in general a good practice for SEO, would also help the general search engines like Google, Bing to index and rank the resource pages from MassBank.

**Comment by meier-rene** [comment]
You are welcome to use our sitemap index file at: https://massbank.eu/MassBank/sitemapindex.xml.
Does this suit your needs?

**Comment by tsufz** [comment]
@newgene, thanks a lot for your request. The schemas are already implemented (view-source:https://massbank.eu/MassBank/RecordDisplay?id=LQB00001&dsn=RIKEN_IMS) and validated with Google SEO. Google warns about the missing `creator` tag. Unfortunately, this is a bigger issue not resolvable with some code snippets. The metadata tags in the MassBank records do not cover schema ready creator tags so far. Curating the datasets is quite tedious because the author tag does not follow any schema.

**Comment by newgene** [comment]
@meier-rene Yes, that's what we need for the crawling purpose. It's enough for us to proceed on our end.

For general SEO purpose, I believe putting `sitemap.xml` at the root URL is more common. And I am not sure if `sitemapindex.xml` is a standard name either, typically just called `sitemap.xml`.

**Comment by tsufz** [comment]
Hi,
We strictly follow https://www.sitemaps.org/de/protocol.html

The crawlers index all our pages, so no worries.

Yours,
Tobias
