### ISSUE TITLE
API is not available

### ISSUE THREAD

**Issue by tsufz** [MassBank/MassBank-web#71]
HTTP Status 404 - /api/services/MassBankAPI

type Status report

message /api/services/MassBankAPI

description The requested resource is not available.
Apache Tomcat/8.0.32 (Ubuntu)

**Comment by meier-rene** [comment]
Missing api is fixed with 2d35dd4. Deployment of api is also integrated in bootstrap.sh and Admin page credentials are automatically injected into axis2.xml.
"api.war" needs to be deployed separately to "MassBank.war". Take a look into bootstrap.sh for instructions. Don't forget to adjust default password (see bootstrap.sh)

**Comment by tsufz** [comment]
Great, looks fine for me. I will deploy to massbank.eu in the next days.
