### ISSUE TITLE
Can not start apache with mpm_worker while php is also enabled

### ISSUE THREAD

**Issue by meier-rene** [MassBank/MassBank-web#82]
The change from mpm_prefork to mpm_worker in commit f54ed50975965cedf78943f3ef4709ccf017df3b breaks startup of Apache for me because php module is also enabled. The error from apache is: "Apache is running a threaded MPM, but your PHP Module is not compiled to be threadsafe.  You need to recompile PHP."
Two solutions:
1. stick with mpm_prefork
2. use libapache2-mod-fastcgi for php

Any Suggestions?

**Comment by tsufz** [comment]
Oh, this is my fault. Piwik uses PHP which is dependent on MPM_prefork worker and does not work with MPM_worker module. So, the MPM_prefork should be used and not the MPM_worker. I changed on MassBank.eu because I use the Piwik of UFZ in order to comply fully with their data privacy policy and to get rid of another tool to manage. I will remove the stuff from bootstrap....
